name: frap_test_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.7.4
  - ipython>=7.30.1
  - pip>=21.3.1
  - numpy>=1.21.4
  - aicsimageio>=4.5.0
  - czifile>=2019.7.2
  - pandas>=1.3.4
  - matplotlib>=3.5.0
  - scipy>=1.7.3
  - scikit-learn>=1.0.1
  - scikit-image>=0.18.3
  - opencv>=4.4.0
  - pyside2=5.13.1
  - pyqtgraph=0.11.0rc0
  - pip:
    - aicspylibczi==3.0.4
